### ISSUE TITLE
Help me out, do you know why I get this error

### ISSUE THREAD

**Issue by Cxmplement** [GizmolabAI/DiscordBot-Flash#7]
client.commands = new Collection();
client.slashCommands = new Collection();
client.config = require("./config.js");
mongoose.connect(client.config.mongooseConnectionString, {
 there's a error with this and the error is 

Info: Make sure you have added the following url to the discord's OAuth callback url section in the developer portal:
http://localhost:3000/callback
===
Dashboard is up and running on port 3000.
(node:10644) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Sellout Economy#3073 is up and ready to go!
C:\Users\ladyg\Videos\DiscordBot-Flash-master\DiscordBot-Flash-master\handler\index.js:46
            .commands.set(arrayOfSlashCommands);
            ^

TypeError: Cannot read properties of undefined (reading 'commands')

**Comment by gizmo-dev** [comment]
you have to add the guild id in handler/index.js
