### ISSUE TITLE
Not a issue but looking for someone to help me upgrade and fix GAwesomeBot

### ISSUE THREAD

**Issue by ghost** [GizmolabAI/DiscordBot-Flash#8]
https://gawesomebot.com/  | https://github.com/GAwesomeBot/bot was once on 5000+ servers and well long story short im the only one who can resurect the bot https://gab.dislist.me is were it lives now ive done additions and fixed the profile command but need alot more help if your down im a no-coder so for me to take this project is a bit of a pain to begin with but im reallllllly looking forward to a reply back! https://gab.dislist.me/activity/servers?q=GAwesomeBot

**Comment by gizmo-dev** [comment]
Heya You can reach out to us on our discord server to talk more on this!
